[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "8M9FqY8bHsN5TE6BZdDxnnZfUATbKKjmLCXjwzuQJ9ZN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/rob.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
